### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by AloncraftMC** [WEGFan/Geometry-Dash-Menu-Music-Randomizer#3]
After clicking on the executable this appears:

Traceback (most recent call last):
  File "menu_music_randomizer.py", line 182, in <module>
  File "menu_music_randomizer.py", line 107, in main
  File "site-packages\pymem\__init__.py", line 220, in open_process_from_id
pymem.exception.CouldNotOpenProcess: Could not open process: 12804

**Comment by WEGFan** [comment]
What's your windows version you are using? Maybe try running as administrator?

**Comment by AloncraftMC** [comment]
Thanks!!! Executing it as an administrator worked. :D This mod is awesome, thx!
